# escape=`

FROM lacledeslan/gamesvr-csgo

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-csgo-test"

HEALTHCHECK NONE

COPY ./dist /app/csgo/

COPY ./dist.linux /app/csgo/

# UPDATE USERNAME
RUN usermod -l CSGOTest CSGO

USER CSGOTest

WORKDIR /app/
