# escape=`

FROM lacledeslan/gamesvr-srcds-csgo:linux

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV IMAGE="gamesvr-srcds-csgo-test:linux"

USER root

COPY ./dist /app/bin/

# CLEAN UP
RUN usermod -l CSGO.Test CSGO

USER CSGO.Test
	
WORKDIR /app/bin/
